### ISSUE TITLE
Possibly outdated confusables.json?

### ISSUE THREAD

**Issue by DavidJacobson** [vhf/confusable_homoglyphs#8]
So I was looking at the confusables.json file, and I'm not sure if it's outdated. It was last committed on Sep 13, 2016, but the official source (https://unicode.org/Public/security/latest/confusables.txt) has a last updated date of: Date: 2017-04-08, 16:13:41 GMT

**Comment by vhf** [comment]
You can update them, see documentation: https://confusable-homoglyphs.readthedocs.io/en/latest/usage.html

**Comment by DavidJacobson** [comment]
👍
